import os, sys; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib import *

reset()
with sync_playwright() as pw:
    b = pw.chromium.launch()

    # ---------- the progress bar, the slow flag, the labels ----------
    ctx, p = as_user(b, 'sales1')
    for number, expected in [('SO-2026-000002', '1 of 7 steps done: With Finance Director'), ('SO-2026-000008', '6 of 7 steps done: On track'), ('SO-2026-000009', 'Delivered: sale complete'), ('SO-2026-000010', 'Stopped: Rejected by the MD')]:
        open_order(p, number)
        check(f'tracker on {number} reads "{expected}"', detail(p).get_by_test_id('tracker-label').inner_text() == expected, detail(p).get_by_test_id('tracker-label').inner_text())
    open_order(p, 'SO-2026-000009'); bar = detail(p).get_by_role('progressbar')
    check('a delivered order\'s bar is full (100%) and has seven segments', bar.get_attribute('aria-valuenow') == '100' and bar.locator('span').count() == 7)
    check('an order only 30 hours with Finance is NOT flagged as slow', row(p, 'SO-2026-000002').get_by_test_id('slow-flag').count() == 0)
    ctx.close()

    ctx, p = as_user(b, 'fd'); p.goto(BASE + '/sales'); p.wait_for_selector('table tbody tr'); show_all(p)
    flag = row(p, 'SO-2026-000003').get_by_test_id('slow-flag')
    check('an order waiting 3 days with Finance is flagged in the list', flag.count() == 1 and 'waiting a while' in flag.inner_text() and '3 days' in flag.inner_text(), flag.inner_text() if flag.count() else 'no flag')
    row(p, 'SO-2026-000003').click(); p.wait_for_selector('[data-testid=holder-banner]')
    check('and the order\'s banner says so too', 'This has been waiting a while' in detail(p).get_by_test_id('holder-banner').inner_text())
    ctx.close()
    ctx, p = as_user(b, 'wm1'); p.goto(BASE + '/sales'); p.wait_for_selector('table tbody tr')
    check('a warehouse manager\'s list is labelled for their warehouse, not "All orders"', p.get_by_role('button', name='Orders at my warehouse (3)').count() == 1, p.locator('[aria-label="Which orders to show"]').inner_text())
    ctx.close()

    # ---------- the dashboard desks, one role at a time ----------
    ctx, p = as_user(b, 'sales1'); p.goto(BASE + '/dashboard'); p.wait_for_selector('[data-testid=officer-greeting]')
    g = p.get_by_test_id('officer-greeting').inner_text()
    check('the Sales Officer is greeted by name and told what is going on', 'Nana' in g and 'moving through the chain' in g and ('need you' in g or 'needs you' in g) and g.startswith(('Good morning', 'Good afternoon', 'Good evening')), g)
    tiles = p.locator('a[href="/sales"]').all_inner_texts()
    check('their stage tiles use the new chain (not-sent 1, Finance 1, MD 1, warehouse 4)', any('With the warehouse' in t and '4' in t for t in tiles) and any('With the MD' in t and '1' in t for t in tiles) and any('Not sent yet' in t for t in tiles), tiles)
    check('no page errors on the officer dashboard', not p.errors, p.errors[:2]); ctx.close()

    ctx, p = as_user(b, 'fd'); p.goto(BASE + '/dashboard'); p.wait_for_selector('text=Sales orders to review')
    sec = p.locator('section', has=p.locator('h3', has_text='Sales orders to review')); sec.get_by_text('SO-2026-000003').wait_for()
    check('Finance\'s desk lists the submitted orders, including the other officer\'s', sec.get_by_text('SO-2026-000002').count() == 1 and sec.get_by_text('SO-2026-000003').count() == 1)
    sec.get_by_text('SO-2026-000002').click(); p.wait_for_selector('text=Who has handled it so far')
    check('opening one shows its receipt and its trail BEFORE the decision', sec.locator('[data-testid=receipt-card]').count() == 1 and sec.get_by_text('Your decision').count() == 1 and sec.locator('[data-testid=receipt-card]').bounding_box()['y'] < sec.get_by_test_id('decision-panel').bounding_box()['y'])
    sec.get_by_role('button', name='Reject', exact=True).click(); conf = sec.get_by_role('button', name='Confirm rejection')
    check('the desk also demands a comment to reject', conf.is_disabled())
    sec.locator('#reject-comment').fill('Receipt is for a different customer'); conf.click(); p.wait_for_timeout(900)
    c = last_call('/reject'); check('the desk\'s comment reached the server', c and c['body'] == {'reason': 'Receipt is for a different customer'}, c)
    check('no page errors on the Finance dashboard', not p.errors, p.errors[:2]); ctx.close()

    ctx, p = as_user(b, 'md'); p.goto(BASE + '/dashboard'); p.wait_for_selector('text=Approved by Finance, ready to release')
    sec = p.locator('section', has=p.locator('h3', has_text='Approved by Finance, ready to release'))
    sec.get_by_text('SO-2026-000004').wait_for(); sec.get_by_text('SO-2026-000004').click(); p.wait_for_selector('text=Who has handled it so far')
    check('the MD\'s desk shows the receipt and Finance\'s comment, with no warehouse choice', sec.locator('[data-testid=receipt-card]').count() == 1 and 'Deposit confirmed on the statement' in sec.inner_text() and sec.locator('input[type=radio]').count() == 0)
    wsec = p.locator('section', has=p.locator('h3', has_text='With the warehouse side'))
    t = wsec.inner_text()
    check('and a section follows every released order through the warehouse side with where each one is', all(x in t for x in ['SO-2026-000005', 'SO-2026-000006', 'SO-2026-000007', 'SO-2026-000008']) and all(x in t for x in ['Awaiting a warehouse', 'Assigned to a warehouse', 'Being processed', 'On track']), t[:300])
    check('no page errors on the MD dashboard', not p.errors, p.errors[:2]); ctx.close()

    reset(); ctx, p = as_user(b, 'sup'); p.goto(BASE + '/dashboard'); p.wait_for_selector('text=choose a warehouse')
    sec = p.locator('section', has=p.locator('h3', has_text='choose a warehouse'))
    sec.get_by_text('SO-2026-000005').click(); panel = sec.get_by_test_id('assign-warehouse'); panel.wait_for(); panel.locator('input[type=radio]').first.wait_for(); p.wait_for_timeout(400)
    check('the Supervisor\'s desk lists released orders and offers the warehouse choice', panel.locator('input[type=radio]').count() == 2 and panel.locator('input[type=radio]').nth(0).is_checked())
    panel.get_by_role('button', name='Assign to this warehouse').click(); p.wait_for_timeout(1000)
    c = last_call('/assign-warehouse'); check('assigning from the desk works', c and c['body']['warehouseId'] == '11111111-1111-4111-8111-111111111111', c)
    wh = p.locator('section', has=p.locator('h3', has_text='At the warehouse'))
    check('the Supervisor also sees what is at the warehouses', all(x in wh.inner_text() for x in ['SO-2026-000006', 'SO-2026-000007', 'SO-2026-000008', 'SO-2026-000005']))
    check('no page errors on the Supervisor dashboard', not p.errors, p.errors[:2]); ctx.close()

    reset(); ctx, p = as_user(b, 'wm1'); p.goto(BASE + '/dashboard'); p.wait_for_selector('h3:has-text("At the warehouse")')
    wh = p.locator('section', has=p.locator('h3', has_text='At the warehouse')); wh.get_by_text('SO-2026-000006').wait_for()
    t = wh.inner_text()
    check('a warehouse manager\'s desk shows only their own warehouse\'s orders', 'SO-2026-000006' in t and 'SO-2026-000007' in t and 'SO-2026-000008' not in t, t[:300])
    wh.get_by_text('SO-2026-000006').click(); wh.get_by_role('button', name='Start processing').click(); p.wait_for_timeout(900)
    check('they can start processing from the desk', last_call('/start-processing') is not None)
    check('no page errors on the warehouse dashboard', not p.errors, p.errors[:2]); ctx.close()

    # ---------- a phone-sized screen ----------
    reset(); ctx, p = as_user(b, 'sales1', viewport={'width': 390, 'height': 844}); open_order(p, 'SO-2026-000001'); d = detail(p)
    overflow = p.evaluate('document.documentElement.scrollWidth - window.innerWidth')
    check('on a phone the order page does not scroll sideways', overflow <= 1, overflow)
    check('on a phone both receipt buttons are on screen and big enough to tap', all(d.get_by_text(t).bounding_box()['height'] >= 30 and d.get_by_text(t).bounding_box()['x'] >= 0 and d.get_by_text(t).bounding_box()['x'] + d.get_by_text(t).bounding_box()['width'] <= 392 for t in ['Take a photo', 'Choose a photo or PDF']))
    ctx.close()
    reset(); ctx, p = as_user(b, 'admin', viewport={'width': 390, 'height': 844}); p.goto(BASE + '/expenses'); p.wait_for_selector('text=EXP-2026-000001')
    p.locator('tr', has_text='EXP-2026-000001').first.get_by_role('button', name='Review').click(); dlg = p.locator('[role=dialog]:has(#review-title)'); dlg.wait_for()
    bb = dlg.bounding_box()
    check('on a phone the review window fits the screen', bb['x'] >= -1 and bb['x'] + bb['width'] <= 391 and bb['y'] >= -1 and bb['y'] + bb['height'] <= 845, bb)
    dlg.get_by_role('button', name='Reject', exact=True).scroll_into_view_if_needed()
    check('and its decision buttons can be reached by scrolling inside it', dlg.get_by_role('button', name='Reject', exact=True).is_visible())
    ctx.close(); b.close()
sys.exit(1 if finish() else 0)
