import os, sys; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lib import *

reset()
with sync_playwright() as pw:
    b = pw.chromium.launch()

    # ============ Sales Officer: isolation, receipts, submit ============
    ctx, p = as_user(b, 'sales1')
    p.goto(BASE + '/sales'); p.wait_for_selector('table tbody tr'); show_all(p)
    numbers = [t.strip() for t in p.locator('tbody tr td:first-child').all_inner_texts()]
    check('officer sees their own orders', 'SO-2026-000001' in numbers and 'SO-2026-000009' in numbers, numbers)
    check("officer does NOT see another officer's order (SO-...0003)", 'SO-2026-000003' not in numbers, numbers)
    check('the list tab says "My orders" with the right count', p.get_by_role('button', name='My orders (9)').count() == 1, p.locator('[aria-label="Which orders to show"]').inner_text())
    check('the list says who holds each order and for how long', p.locator('thead th', has_text='With').count() == 1 and 'Finance Director' in row(p, 'SO-2026-000002').inner_text())
    s, _ = http('/api/sales-orders/o3', token='tok-sales1'); check('the other officer\'s order is "not found" if asked for directly', s == 404, s)
    s, lst = http('/api/sales-orders', token='tok-sales2'); check('the other officer sees only theirs', s == 200 and [o['id'] for o in lst['data']] == ['o3'], lst)

    # --- a draft: upload receipts from the computer (a phone's camera uses the same inputs)
    open_order(p, 'SO-2026-000001'); d = detail(p)
    check('a draft shows the receipts panel with both ways to add a receipt', d.get_by_text('Take a photo').count() == 1 and d.get_by_text('Choose a photo or PDF').count() == 1)
    check('there is no link box any more', d.get_by_placeholder('link', exact=False).count() == 0 and d.get_by_text('Google Drive', exact=False).count() == 0)
    cam = d.locator('[data-testid=receipt-camera-input]'); chooser = d.locator('[data-testid=receipt-file-input]')
    check('"Take a photo" opens a phone\'s rear camera (capture + images only)', cam.get_attribute('capture') == 'environment' and cam.get_attribute('accept') == 'image/*')
    check('"Choose a photo or PDF" accepts images and PDFs', 'application/pdf' in chooser.get_attribute('accept') and 'image/*' in chooser.get_attribute('accept'))
    d.get_by_label('What the receipt is for').fill('50% deposit, mobile money')
    chooser.set_input_files({'name': 'IMG_2041.png', 'mimeType': 'image/png', 'buffer': png()})
    d.locator('[data-testid=receipt-card]').first.wait_for()
    p.wait_for_timeout(800)
    c = last_call('/receipts')
    check('the photo reached the server as a real file, shrunk to JPEG, with its note', c and c['file']['type'] == 'image/jpeg' and c['file']['name'].endswith('.jpg') and c['fields'].get('note') == '50% deposit, mobile money', c)
    card = d.locator('[data-testid=receipt-card]').first
    check('the receipt card shows the name, who added it, and the note', 'IMG_2041.jpg' in card.inner_text() and 'Nana Yeboah' in card.inner_text() and '50% deposit' in card.inner_text(), card.inner_text())
    check('a thumbnail of the photo really loads (fetched with the sign-in, not a public link)', card.locator('img').evaluate('i => i.complete && i.naturalWidth > 0'))
    card.locator('button[aria-label^="Open receipt"]').first.click()
    p.wait_for_selector('[role=dialog][aria-label=Receipt]')
    check('clicking the thumbnail opens it full size', p.locator('[role=dialog][aria-label=Receipt] img').evaluate('i => i.complete && i.naturalWidth > 0'))
    p.keyboard.press('Escape'); p.locator('[role=dialog][aria-label=Receipt] button[aria-label=Close]').click()
    chooser.set_input_files({'name': 'statement.pdf', 'mimeType': 'application/pdf', 'buffer': PDF}); p.wait_for_timeout(900)
    check('a PDF is accepted too, shown with a document icon', d.locator('[data-testid=receipt-card]').count() == 2 and d.locator('[data-testid=receipt-card]').nth(1).locator('img').count() == 0)
    chooser.set_input_files({'name': 'notes.jpg', 'mimeType': 'image/jpeg', 'buffer': b'this is only text pretending to be a photo'}); p.wait_for_timeout(900)
    check('a file that is not really a photo or PDF is refused with a clear message', d.get_by_text('Only photos (JPEG, PNG or WebP) and PDF files', exact=False).count() == 1 and d.locator('[data-testid=receipt-card]').count() == 2, d.inner_text()[-300:])
    d.locator('[data-testid=receipt-card]').nth(1).locator('button[aria-label^="Remove receipt"]').click(); p.wait_for_timeout(700)
    check('while it is a draft a receipt can be removed', d.locator('[data-testid=receipt-card]').count() == 1)
    check('the draft shows no "who holds it" banner, and the trail has the creation', d.locator('[data-testid=holder-banner]').count() == 0 and d.locator('[data-testid=timeline-event]').count() >= 2)
    d.get_by_test_id('submit-order').click(); p.wait_for_timeout(900)
    check('sending it moves it to Finance and says who has it', d.locator('[data-testid=holder-banner]').inner_text().startswith('With the Finance Director'), d.locator('[data-testid=holder-banner]').inner_text() if d.locator('[data-testid=holder-banner]').count() else 'no banner')
    check('the trail now says it was sent, by whom', 'Sent to the Finance Director' in d.inner_text() and 'Nana Yeboah, Sales Officer' in d.inner_text())
    check('once submitted, receipts can no longer be removed (they are the record)', d.locator('button[aria-label^="Remove receipt"]').count() == 0)
    check('but a further receipt can still be added', d.get_by_text('Choose a photo or PDF').count() == 1)

    # --- later stages as the officer sees them
    open_order(p, 'SO-2026-000010'); d = detail(p)
    check('a rejected order shows who rejected it, their role, and WHY', 'Rejected by Kwame Asante, Managing Director' in d.locator('[data-testid=banner-rejected]').inner_text() and 'over the credit limit' in d.locator('[data-testid=banner-rejected]').inner_text(), d.locator('[data-testid=banner-rejected]').inner_text() if d.locator('[data-testid=banner-rejected]').count() else 'none')
    check('the rejection comment also appears in the trail', 'over the credit limit' in d.locator('[data-testid=timeline-event]').last.inner_text())
    open_order(p, 'SO-2026-000008'); d = detail(p)
    check('an order on track shows the driver, vehicle and expected arrival', all(x in d.locator('[data-testid=tracking-card]').inner_text() for x in ['Yaw Boateng', 'GT-1234-22', 'Expected']), d.locator('[data-testid=tracking-card]').inner_text() if d.locator('[data-testid=tracking-card]').count() else 'none')
    check('the officer gets no warehouse buttons on it', d.get_by_text('Confirm delivered').count() == 0 and d.get_by_text('Start processing').count() == 0)
    check('the tracker has seven steps, "On track" done and "Delivered" current', d.locator('ol >> li').filter(has_text='Delivered').count() >= 1)
    open_order(p, 'SO-2026-000009'); d = detail(p)
    check('a delivered order says so', 'Sale complete' in d.locator('[data-testid=banner-delivered]').inner_text())
    check('no page errors for the officer', not p.errors, p.errors[:2]); ctx.close()

    # ============ Finance Director ============
    ctx, p = as_user(b, 'fd')
    p.goto(BASE + '/sales'); p.wait_for_selector('table tbody tr'); show_all(p)
    numbers = [t.strip() for t in p.locator('tbody tr td:first-child').all_inner_texts()]
    check('Finance sees every order, including the other officer\'s', 'SO-2026-000003' in numbers and 'SO-2026-000001' in numbers, numbers)
    check('the tab says "All orders"', p.get_by_role('button', name='All orders (10)').count() == 1)
    open_order(p, 'SO-2026-000002'); d = detail(p)
    check('Finance sees the uploaded receipt thumbnail before deciding', d.locator('[data-testid=receipt-card] img').first.evaluate('i => i.complete && i.naturalWidth > 0'))
    check('Finance cannot add or remove receipts', d.get_by_text('Choose a photo or PDF').count() == 0 and d.locator('button[aria-label^="Remove receipt"]').count() == 0)
    r_y = d.locator('[data-testid=receipts-panel]').bounding_box()['y']; dec_y = d.locator('[data-testid=decision-panel]').bounding_box()['y']; items_y = d.get_by_text('What was ordered').bounding_box()['y']
    check('the details and receipts come BEFORE the decision on the page', items_y < r_y < dec_y, (items_y, r_y, dec_y))
    d.get_by_role('button', name='Reject', exact=True).click()
    conf = d.get_by_role('button', name='Confirm rejection')
    check('rejecting asks for a comment, and cannot be confirmed without one', conf.is_disabled() and d.get_by_text('A comment is required when rejecting').count() == 1)
    d.locator('#reject-comment').fill('ab'); check('two letters is not enough', conf.is_disabled())
    d.locator('#reject-comment').fill('   '); check('blank spaces are not a comment', conf.is_disabled())
    d.locator('#reject-comment').fill('Receipt shows GHS 2,000, not the GHS 5,000 deposit'); check('a real comment enables it', conf.is_enabled())
    conf.click(); p.wait_for_timeout(1000)
    c = last_call('/reject'); check('the exact comment was sent with the rejection', c and c['body'] == {'reason': 'Receipt shows GHS 2,000, not the GHS 5,000 deposit'}, c)
    check('the order shows rejected, by Finance, with the reason', 'Rejected by Kwesi Appiah, Finance Director' in d.locator('[data-testid=banner-rejected]').inner_text() and 'GHS 5,000 deposit' in d.locator('[data-testid=banner-rejected]').inner_text())
    check('the decision buttons are gone afterwards', d.get_by_test_id('decision-panel').count() == 0)
    open_order(p, 'SO-2026-000003'); d = detail(p)
    check('an order with no receipt says so plainly', 'No payment receipt has been uploaded' in d.inner_text())
    d.get_by_placeholder('Optional note for the Managing Director', exact=False).fill('Deposit seen on the statement')
    d.get_by_role('button', name='Approve and send to the MD').click(); p.wait_for_timeout(1000)
    c = last_call('/approve'); check('approval carries the optional note', c and c['body'] == {'note': 'Deposit seen on the statement'}, c)
    check('it then sits with the Managing Director', 'With the Managing Director' in d.locator('[data-testid=holder-banner]').inner_text())
    check('the trail shows Finance\'s note', 'Deposit seen on the statement' in d.inner_text() and 'Kwesi Appiah, Finance Director' in d.inner_text())
    check('no page errors for Finance', not p.errors, p.errors[:2]); ctx.close()

    # ============ Managing Director ============
    ctx, p = as_user(b, 'md')
    open_order(p, 'SO-2026-000004'); d = detail(p)
    check('the MD sees the receipt and Finance\'s comment before deciding', d.locator('[data-testid=receipt-card]').count() == 1 and 'Deposit confirmed on the statement' in d.inner_text())
    check('the MD no longer picks a warehouse (no warehouse choices at all)', d.locator('input[type=radio]').count() == 0)
    check('the MD can release or reject', d.get_by_role('button', name='Release to the Warehouse Supervisor').count() == 1 and d.get_by_role('button', name='Reject', exact=True).count() == 1)
    d.get_by_placeholder('Optional instruction for the Warehouse Supervisor').fill('Deliver before noon')
    d.get_by_role('button', name='Release to the Warehouse Supervisor').click(); p.wait_for_timeout(1000)
    c = last_call('/release'); check('release sends only the instruction, no warehouse', c and c['body'] == {'note': 'Deliver before noon'}, c)
    check('it now waits for the Warehouse Supervisor', 'With the Warehouse Supervisor' in d.locator('[data-testid=holder-banner]').inner_text())
    open_order(p, 'SO-2026-000003'); d = detail(p)
    d.get_by_role('button', name='Reject', exact=True).click()
    check('the MD cannot reject without a comment either', d.get_by_role('button', name='Confirm rejection').is_disabled())
    d.locator('#reject-comment').fill('Customer is over the credit limit'); d.get_by_role('button', name='Confirm rejection').click(); p.wait_for_timeout(1000)
    check('the MD\'s rejection shows who, in which role, and why', 'Rejected by Kwame Asante, Managing Director' in d.locator('[data-testid=banner-rejected]').inner_text() and 'credit limit' in d.locator('[data-testid=banner-rejected]').inner_text())
    check('no page errors for the MD', not p.errors, p.errors[:2]); ctx.close()

    # ============ Warehouse Supervisor assigns ============
    ctx, p = as_user(b, 'sup')
    open_order(p, 'SO-2026-000005'); d = detail(p)
    panel = d.get_by_test_id('assign-warehouse')
    check('the Supervisor sees the warehouses and which can cover the order', panel.locator('input[type=radio]').count() == 2 and 'can cover the whole order' in panel.inner_text() and 'cannot cover it' in panel.inner_text())
    check('the warehouse that cannot cover it cannot be chosen, and says why', panel.locator('input[type=radio]').nth(1).is_disabled() and 'needs 50, has 10' in panel.inner_text())
    check('the one that can is pre-selected', panel.locator('input[type=radio]').nth(0).is_checked())
    panel.get_by_role('button', name='Assign to this warehouse').click(); p.wait_for_timeout(1000)
    c = last_call('/assign-warehouse'); check('assigning sends the warehouse', c and c['body'].get('warehouseId') == '11111111-1111-4111-8111-111111111111', c)
    check('the order is now assigned and sits with the warehouse team', 'Assigned to a warehouse' in row(p, 'SO-2026-000005').inner_text() and 'With the Warehouse team' in d.locator('[data-testid=holder-banner]').inner_text())
    check('the trail names the warehouse and the Supervisor', 'Assigned to Tamale Warehouse' in d.inner_text() and 'Efua Darko, Warehouse Supervisor' in d.inner_text())
    check('before processing starts, the Supervisor can still move it', d.get_by_text('Move it to a different warehouse').count() >= 1)
    check('no page errors for the Supervisor', not p.errors, p.errors[:2]); ctx.close()

    # ============ Warehouse manager: process, on track, delivered ============
    ctx, p = as_user(b, 'wm1')
    p.goto(BASE + '/sales'); p.wait_for_selector('table tbody tr'); show_all(p)
    numbers = [t.strip() for t in p.locator('tbody tr td:first-child').all_inner_texts()]
    check('a warehouse manager sees only orders assigned to their own warehouse', set(numbers) == {'SO-2026-000005', 'SO-2026-000006', 'SO-2026-000007', 'SO-2026-000009'}, numbers)
    s, _ = http('/api/sales-orders/o8', token='tok-wm1'); check('another warehouse\'s order is "not found" to them', s == 404, s)
    s, _ = http('/api/sales-orders/o6', token='tok-wm2'); check('and theirs is not found to the other warehouse\'s manager', s == 404, s)
    open_order(p, 'SO-2026-000006'); d = detail(p); steps = d.get_by_test_id('warehouse-steps')
    check('step 1 is processing', 'step 1 of 3: processing' in steps.inner_text().lower())
    steps.get_by_role('button', name='Start processing').click(); p.wait_for_timeout(1000)
    check('it moves to Being processed', 'Being processed' in row(p, 'SO-2026-000006').inner_text())
    steps = d.get_by_test_id('warehouse-steps')
    check('step 2 asks for the driver, vehicle and expected arrival', 'step 2 of 3: on track' in steps.inner_text().lower() and steps.get_by_label("Driver's name").count() == 1 and steps.get_by_label('Vehicle number').count() == 1)
    steps.get_by_label("Driver's name").fill('Yaw Boateng'); steps.get_by_label('Vehicle number').fill('GT-1234-22'); steps.locator('input[type=datetime-local]').fill('2026-10-08T14:00')
    steps.get_by_role('button', name='Mark on track: it has left').click(); p.wait_for_timeout(1000)
    c = last_call('/dispatch'); check('the tracking details were sent', c and c['body']['driverName'] == 'Yaw Boateng' and c['body']['vehicleNumber'] == 'GT-1234-22' and c['body']['expectedDeliveryAt'].startswith('2026-10-08'), c)
    check('the order is "On track" with a tracking card', 'On track' in row(p, 'SO-2026-000006').inner_text() and 'Yaw Boateng' in d.locator('[data-testid=tracking-card]').inner_text())
    steps = d.get_by_test_id('warehouse-steps'); steps.get_by_label('Optional note, e.g. who received it').fill('Received by Mr Mensah')
    steps.get_by_role('button', name='Confirm delivered').click(); steps.get_by_role('button', name='Yes, confirm delivery').click(); p.wait_for_timeout(1000)
    c = last_call('/fulfill'); check('delivery was confirmed with the note', c and c['body'] == {'note': 'Received by Mr Mensah'}, c)
    check('the order is Delivered, sale complete', 'Sale complete' in d.locator('[data-testid=banner-delivered]').inner_text())
    ev = d.locator('[data-testid=timeline-event]').all_inner_texts()
    check('the whole story is in the trail, in order, with every person named', len(ev) >= 5 and 'Processing started' in ' '.join(ev) and 'On track' in ' '.join(ev) and 'Delivered' in ev[-1] and 'Kwabena Adjei, Warehouse Manager' in ev[-1], ev)
    check('no page errors for the warehouse manager', not p.errors, p.errors[:2]); ctx.close()
    b.close()
sys.exit(1 if finish() else 0)
